---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
  stages:
    Release:
      cfCredentialsId: "cfcredentials"
stages:
  Build:
    source: helloworldui5
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: false
  Acceptance:
    npmExecuteEndToEndTests: false
    cloudFoundryDeploy: false
  Compliance:
    sonarExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "473338bbtrial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "QAS"
    credentialsId: "std-tms"
